version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend.Dockerfile
      target: backend-build
    command: npm run start:dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
      - ./shared:/usr/src/backend/node_modules/app-shared
    ports:
      - ${SERVER_PORT:?err}:${SERVER_PORT:?err}
    networks:
      - app-frontend-backend-net
    depends_on:
        - bitrix-server-nginx

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
      target: frontend-build
    environment:
      - WATCHPACK_POLLING=true
    command: npm run start
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
      - ./shared:/usr/src/frontend/node_modules/app-shared
    ports:
      - ${FRONTEND_PORT:?err}:${FRONTEND_PORT:?err}
    networks:
      - app-frontend-backend-net
    depends_on:
      - backend

  bitrix-server-nginx:
      container_name: bitrix-server-nginx
      image: nginx
      volumes:
          - ./bitrix/docker/nginx/apache.conf.template:/etc/nginx/conf.d/apache.conf.template
      ports:
          - ${BX_SERVER_PORT:?err}:${BX_SERVER_PORT:?err}
      environment:
          - DOLLAR=$$
          - PORT=${BX_SERVER_PORT:?err}
          - APACHE_HOST=${BX_APACHE_SERVER_HOST:?err}
          - APACHE_PORT=${BX_APACHE_SERVER_PORT:?err}
      command: /bin/bash -c "envsubst < /etc/nginx/conf.d/apache.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      networks:
          - app-frontend-backend-net
      depends_on:
          - bitrix-server-php-apache
  bitrix-server-php-apache:
      container_name: bitrix-server-php-apache
      build: ./bitrix
      environment:
          - APACHE_RUN_USER=www-data
      volumes:
          - ./bitrix/docker/apache/php.ini:/usr/local/etc/php/php.ini
          - ./bitrix/:/var/www/html
          - /var/www/html/bitrix
          - ./bitrix/bitrix/cache:/var/www/html/bitrix/cache
          - /var/www/html/vendor
      ports:
          - ${BX_APACHE_SERVER_PORT:?err}:${BX_APACHE_SERVER_PORT:?err}
      networks:
          - app-frontend-backend-net
      depends_on:
          - bitrix-server-database

  bitrix-server-database:
      container_name: bitrix-server-database
      image: "mysql:5.6"
      volumes:
          - ./bitrix/docker/db:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      networks:
          - app-frontend-backend-net



networks:
  app-frontend-backend-net:
    driver: bridge
